---

- name: Get k3s_kube_config
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_kube_config_encoded
  check_mode: false
  delegate_to: "{{ groups['cluster_control_plane'][0] }}"

- name: Decode remote content
  ansible.builtin.set_fact:
    k3s_kube_config: "{{ k3s_kube_config_encoded.content | b64decode }}"

- name: Create kube config directory
  ansible.builtin.file:
    dest: .kube
    state: directory
    mode: "0745"
  register: k3s_config_folder_created
  delegate_to: 127.0.0.1

- name: "Create local kube config"
  ansible.builtin.copy:
    dest: .kube/config
    content: '{{ k3s_kube_config }}'
    mode: '0600'
  register: k3s_config_created
  delegate_to: 127.0.0.1

- name: Update kubeconfig server entry
  ansible.builtin.lineinfile:
    dest: "{{ home }}/.kube/config"
    regex: '^.*server'
    line: "    server: https://{{ groups['cluster_control_plane'][0] }}:6443"
  register: kubeconfig_servername_set
  delegate_to: 127.0.0.1
